# Generated by Django 5.0.6 on 2024-06-05 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_user_is_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_user': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
