# Generated by Django 5.0.6 on 2024-06-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='fee',
            field=models.CharField(max_length=50),
        ),
    ]
